name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Python のセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Poetry のセットアップ
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "2.1.1"

      - name: キャッシュの設定
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: 依存関係のインストール
        run: poetry install

      - name: 必要なGUIライブラリのインストール
        run: sudo apt-get install -y libxkbcommon-x11-0 libgl1-mesa-dev

      - name: 追加GUIライブラリのインストール
        run: sudo apt-get install -y x11-xkb-utils x11-xserver-utils xserver-xorg-core xfonts-base x11-utils

      - name: Xvfb機能の検証
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
          sleep 3
          xrandr

      - name: テストの実行（GUI テスト含む）
        run: xvfb-run -a poetry run pytest tests/unit tests/integration -v
