name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Python のセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Poetry のセットアップ
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "2.1.1"

      - name: キャッシュの設定
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-
      
      - name: 必要なライブラリのインストール
        run: sudo apt-get update && sudo apt-get install -y xvfb libgl1 libxi6 libgconf-2-4 libnss3 libxss1 libasound2 libgtk-3-0

      - name: 依存関係のインストール
        run: poetry install

      - name: テストの実行（GUI テストを含まない)
        run: poetry run pytest tests/unit tests/integration -v
